# Generated by Django 5.2.7 on 2025-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('VALOR_FIJO', 'Valor Fijo'), ('2X1', '2x1')], max_length=20)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=False)),
                ('es_general', models.BooleanField(default=False)),
                ('clientes_beneficiados', models.ManyToManyField(blank=True, related_name='promociones_beneficiadas', to='clientes.cliente')),
                ('productos', models.ManyToManyField(blank=True, to='productos.producto')),
            ],
        ),
    ]
