# Generated by Django 5.2.7 on 2025-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Porcentaje de descuento aplicado a los productos de la categoría.', max_digits=5),
            preserve_default=False,
        ),
    ]
