# Generated by Django 5.2.7 on 2025-11-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campana_valor_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='valor_descuento',
        ),
    ]
